### ISSUE TITLE
getParent( pathOrKey ) - Get the parent content by path or key

### ISSUE THREAD

**Issue by rbrastad** [enonic/lib-util#16]

**Comment by rbrastad** [comment]
I'll take this

**Comment by ComLock** [comment]
Have a look at this https://github.com/enonic/lib-util/compare/content.getAncestors#diff-946c6bbb2308deb87f33b74dfb79287fR83

**Comment by ComLock** [comment]
And here some other code I found:
```
/**
 * Return parent content, based on path
 * @param content
 * @returns {*}
 */
function getParent(content){
    let pathArray = content._path.split('/');
    if(pathArray.length < 3) { //Can't get much higher than this
        return null;
    }
    pathArray.pop();
    const parentPath = pathArray.join('/');
    const result = xpContentQuery({
        query: `(_path = '/content${parentPath}')`
    });
    return result.hits[0];
}
```

**Comment by alansemenov** [comment]
@rbrastad What is the status of this one?

**Comment by ComLock** [comment]
@rbrastad @alansemenov I have implemented and tested this https://github.com/enonic/lib-util/blob/master/src/main/resources/site/lib/enonic/util/content/getParent.es but its not released yet.

**Comment by ComLock** [comment]
getParent() is already released
