### ISSUE TITLE
Add function for removing html tags

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-util#20]
using this code in the Metafields app now. Might be useful for others. Not sure if it should go into values, or content, or data, or a new security-file. Probably values.js.

```
	// Strip away all html tags, in case there's any in the description.
	var regex = /(<([^>]+)>)/ig;
	metaDescription = metaDescription.replace(regex, "");
```

**Comment by poi33** [comment]
I really don't want to add this to the util lib. 
"HTML-plus-regexp will liquify the n​erves of the sentient whilst you observe, your psyche withering in the onslaught of horror." To mention one argument against it. 
If we really want to parse html and change the dom structure we should write a proper html parser and include it in another lib.

**Comment by rymsha** [comment]
Simple valid HTML `<a alt=">" href="#">text<\a>` breaks this regexp. Do not use it, please.

Although having a function to strip away html tags could be useful.

**Comment by poi33** [comment]
Stripping html tags can be useful, but we would have to parse the dom properly.
So might want to parse the dom into a useful structure and manipulate it. 🤔 This sounds like it should be a seperate lib.

**Comment by sigdestad** [comment]
Indeed..

**Comment by Bellfalasch** [comment]
Why are you reviving suggestions I made 3 years ago guys? ;P These libs are yours no, just purge them of all my outdated suggestions, plz =)

**Comment by poi33** [comment]
There are not a lot of people creating feature requests so this is all i have to go on. 😿 
And this is an ok feature request. Just the suggested implementation is not so good. 

Closing this issue as it will be to big for lib-util.
