### ISSUE TITLE
region.get() - Object.values is not a function

### ISSUE THREAD

**Issue by hjelmevold** [enonic/lib-util#26]
The rewrite inside region.es that uses Object.values produces an error when any component (such as a new empty layout) is sent into the get() function.

The old code using for…in instead of Object.values seems to work, though. Here is the old code:
https://github.com/enonic/lib-util/blob/c8a477392d58d4349f9af50c437585a1d29e09c9/src/main/resources/site/lib/enonic/util/region.js#L19

Also, since 7.0 does not include a name property inside the region object, the region name should be added to each object inside the array that is returned, so that the name is not lost when calling this function.

**Comment by sigdestad** [comment]
Is the name thing a breaking change?
