### ISSUE TITLE
Remove Gradle wrapper?

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/lib-util#9]
Libs for XP are never built independently, they are included in other libs. So ... we have no use of the gradle wrapper files right? Should be removed yeah?

**Comment by Bellfalasch** [comment]
If the one that builds the lib jars doesn't need it ofc :P But could be added to gitignore in that case.

Or perhaps we should keep it for others to fork the project easier without having Gradle installed.

**Comment by zenglian** [comment]
It's easier to install gradle than these "wrappers" if necessary.
